export enum EXPRESSION {
    ADD = "EXPRESSION_ADD",
    ADD_BULK = "EXPRESSION_ADD_BULK",
    REMOVE = "EXPRESSION_REMOVE",
    ACTIVATE = "EXPRESSION_ACTIVATE",
    DEACTIVATE = "EXPRESSION_DEACTIVATE",
    LOAD = "EXPRESSION_LOAD",
    SAVE = "EXPRESSION_SAVE"
}

export const EXPRESSION_OPTIONS = [
    EXPRESSION.ADD,
    EXPRESSION.ADD_BULK,
    EXPRESSION.REMOVE,
    EXPRESSION.ACTIVATE,
    EXPRESSION.DEACTIVATE,
    EXPRESSION.LOAD,
    EXPRESSION.SAVE,
];
