export enum EXPRESSION_EXCEPTION {
    ADD = "EXPRESSION_EXCEPTION_ADD",
    REMOVE = "EXPRESSION_EXCEPTION_REMOVE",
    ACTIVATE = "EXPRESSION_EXCEPTION_ACTIVATE",
    DEACTIVATE = "EXPRESSION_EXCEPTION_DEACTIVATE"
}

export const EXPRESSION_EXCEPTION_OPTIONS = [
    EXPRESSION_EXCEPTION.ADD,
    EXPRESSION_EXCEPTION.REMOVE,
    EXPRESSION_EXCEPTION.ACTIVATE,
    EXPRESSION_EXCEPTION.DEACTIVATE
];
