export enum EXPRESSION_FINDER {
    ADD = "EXPRESSION_FINDER_ADD",
    REMOVE = "EXPRESSION_FINDER_REMOVE",
    ACTIVATE = "EXPRESSION_FINDER_ACTIVATE",
    DEACTIVATE = "EXPRESSION_FINDER_DEACTIVATE"
}

export const EXPRESSION_FINDER_OPTIONS = [
    EXPRESSION_FINDER.ADD,
    EXPRESSION_FINDER.REMOVE,
    EXPRESSION_FINDER.ACTIVATE,
    EXPRESSION_FINDER.DEACTIVATE
];
