name: Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install Packages
      run: yarn install
    
    - name: Publish Package
      run: yarn run publish
      env: 
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
