# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    runs-on: runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # run 2 copies of the current job in parallel
        # and they will load balance all specs
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install Packages
      run: yarn install
    
    - name: Publish Package
      run: yarn run publish
      env: 
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
