export enum SYSTEM_LIFE_CYCLE {
    LOAD = "SYSTEM_LIFE_CYCLE_LOAD",
    SAVE = "SYSTEM_LIFE_CYCLE_SAVE",
}

export const SYSTEM_LIFE_CYCLE_OPTIONS = [
    SYSTEM_LIFE_CYCLE.LOAD,
    SYSTEM_LIFE_CYCLE.SAVE,
];
